[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; upgrade-insecure-requests; form-action 'none'; base-uri 'none'; frame-ancestors 'none'"