apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-demo.name" . }}
  labels:
    {{- include "spring-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spring-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        {{- include "spring-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: spring-demo:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 9" ]
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: http
              initialDelaySeconds: 5
              periodSeconds: 1
          resources:
            requests:
              cpu: 1000m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 256Mi
